name: Build and Deploy Presentation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    uses: IndrajeetPatil/workflows/.github/workflows/build-presentation-python.yaml@b9e1915cfa052d25e2164354817b50f00b9d72da
    permissions:
      contents: read
      pages: write
      id-token: write
